spring:
  application:
    name: dummy-service # Identifier of this application

server.port: 3333

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # URL of the eureka server for registration